### ISSUE TITLE
Select word by double click mouse can't work sometimes

### ISSUE THREAD

**Issue by zijianyue** [mlf176f2/tabbar-ruler.el#19]
Open my init file ,then Split window right, and open an elisp file, then it can't select word by double clicking mouse in the elisp file. Can you try to reproduce this issue and fix it .I tested version 0.44 and the Aug 5, 2015 version, the issue are the same

**Comment by mlf176f2** [comment]
I can reproduce it,  I haven't figured out how to fix it yet.   If you figure out how,  let me know.

**Comment by zijianyue** [comment]
I deleted (tabbar-display-update) from these functions on-modifying-buffer ,after-modifying-buffer and on-saving-buffer, and it works well on emacs 24.5 now

**Comment by mlf176f2** [comment]
Thanks for the information.  I have updated so these functions do are not removed from on-modifying buffer, etc. and I can still select the word by double clicking the words.  If it doesn't work for you, let me know.
