### ISSUE TITLE
After enable theme or disable theme, the face of tab seems not right

### ISSUE THREAD

**Issue by zijianyue** [mlf176f2/tabbar-ruler.el#20]
To solve this ,I added below advice 
(defadvice enable-theme(after enable-theme-after activate)
  (tabbar-install-faces))
(defadvice disable-theme(after disable-theme-after activate)
  (tabbar-install-faces))

**Comment by zijianyue** [comment]
To reproduce this issue ,you can switch theme between light and dark

**Comment by mlf176f2** [comment]
Thanks so much!
